[package]
name = "query"
version = "0.1.0"
edition = "2021"

[[example]]
name = "dialect"
[[example]]
name = "polars"

[dependencies]
tokio = { workspace = true }
reqwest = { workspace = true }
sqlparser = "0.49.0"
polars = { version = "0.41.3", features = ["json", "lazy"] }